# SPDX-License-Identifier: AGPL-3.0-or-later
"""Static permission names and default role bundles for future auth."""

from __future__ import annotations

from types import MappingProxyType

PERMISSION_ADMIN_USERS = "admin.users"
PERMISSION_ADMIN_CONFIG = "admin.config"
PERMISSION_BACKUP_EXPORT = "backup.export"
PERMISSION_BACKUP_RESTORE = "backup.restore"
PERMISSION_AUDIT_READ = "audit.read"
PERMISSION_CONTACTS_READ = "contacts.read"
PERMISSION_CONTACTS_WRITE = "contacts.write"
PERMISSION_FINANCE_READ = "finance.read"
PERMISSION_FINANCE_WRITE = "finance.write"
PERMISSION_INVENTORY_READ = "inventory.read"
PERMISSION_INVENTORY_WRITE = "inventory.write"
PERMISSION_INVOICES_READ = "invoices.read"
PERMISSION_INVOICES_WRITE = "invoices.write"
PERMISSION_JOBS_READ = "jobs.read"
PERMISSION_JOBS_WRITE = "jobs.write"
PERMISSION_LOGS_READ = "logs.read"
PERMISSION_MANUFACTURING_READ = "manufacturing.read"
PERMISSION_MANUFACTURING_RUN = "manufacturing.run"
PERMISSION_RECIPES_READ = "recipes.read"
PERMISSION_RECIPES_WRITE = "recipes.write"
PERMISSION_SETTINGS_READ = "settings.read"
PERMISSION_SETTINGS_MANAGE = "settings.manage"
PERMISSION_SESSIONS_MANAGE = "sessions.manage"
PERMISSION_SYSTEM_READ = "system.read"
PERMISSION_SYSTEM_ADMIN = "system.admin"
PERMISSION_SYSTEM_RESTART = "system.restart"
PERMISSION_UPDATES_CHECK = "updates.check"
PERMISSION_UPDATES_STAGE = "updates.stage"
PERMISSION_USERS_READ = "users.read"
PERMISSION_USERS_MANAGE = "users.manage"

ALL_PERMISSIONS = tuple(
    sorted(
        {
            PERMISSION_ADMIN_CONFIG,
            PERMISSION_ADMIN_USERS,
            PERMISSION_AUDIT_READ,
            PERMISSION_BACKUP_EXPORT,
            PERMISSION_BACKUP_RESTORE,
            PERMISSION_CONTACTS_READ,
            PERMISSION_CONTACTS_WRITE,
            PERMISSION_FINANCE_READ,
            PERMISSION_FINANCE_WRITE,
            PERMISSION_INVENTORY_READ,
            PERMISSION_INVENTORY_WRITE,
            PERMISSION_INVOICES_READ,
            PERMISSION_INVOICES_WRITE,
            PERMISSION_JOBS_READ,
            PERMISSION_JOBS_WRITE,
            PERMISSION_LOGS_READ,
            PERMISSION_MANUFACTURING_READ,
            PERMISSION_MANUFACTURING_RUN,
            PERMISSION_RECIPES_READ,
            PERMISSION_RECIPES_WRITE,
            PERMISSION_SETTINGS_MANAGE,
            PERMISSION_SETTINGS_READ,
            PERMISSION_SESSIONS_MANAGE,
            PERMISSION_SYSTEM_ADMIN,
            PERMISSION_SYSTEM_READ,
            PERMISSION_SYSTEM_RESTART,
            PERMISSION_UPDATES_CHECK,
            PERMISSION_UPDATES_STAGE,
            PERMISSION_USERS_MANAGE,
            PERMISSION_USERS_READ,
        }
    )
)

OWNER_ROLE_KEY = "owner"
OPERATOR_ROLE_KEY = "operator"
VIEWER_ROLE_KEY = "viewer"

OWNER_PERMISSIONS = tuple(
    sorted(
        {
            *ALL_PERMISSIONS,
        }
    )
)

OPERATOR_PERMISSIONS = tuple(
    sorted(
        {
            PERMISSION_BACKUP_EXPORT,
            PERMISSION_CONTACTS_READ,
            PERMISSION_CONTACTS_WRITE,
            PERMISSION_FINANCE_READ,
            PERMISSION_INVENTORY_READ,
            PERMISSION_INVENTORY_WRITE,
            PERMISSION_INVOICES_READ,
            PERMISSION_INVOICES_WRITE,
            PERMISSION_JOBS_READ,
            PERMISSION_JOBS_WRITE,
            PERMISSION_LOGS_READ,
            PERMISSION_MANUFACTURING_READ,
            PERMISSION_MANUFACTURING_RUN,
            PERMISSION_RECIPES_READ,
            PERMISSION_RECIPES_WRITE,
            PERMISSION_SYSTEM_READ,
            PERMISSION_UPDATES_CHECK,
        }
    )
)

VIEWER_PERMISSIONS = tuple(
    sorted(
        {
            PERMISSION_FINANCE_READ,
            PERMISSION_INVENTORY_READ,
            PERMISSION_INVOICES_READ,
            PERMISSION_CONTACTS_READ,
            PERMISSION_JOBS_READ,
            PERMISSION_LOGS_READ,
            PERMISSION_MANUFACTURING_READ,
            PERMISSION_RECIPES_READ,
            PERMISSION_SETTINGS_READ,
            PERMISSION_SYSTEM_READ,
            PERMISSION_UPDATES_CHECK,
        }
    )
)

DEFAULT_ROLE_BUNDLES = MappingProxyType(
    {
        OWNER_ROLE_KEY: OWNER_PERMISSIONS,
        OPERATOR_ROLE_KEY: OPERATOR_PERMISSIONS,
        VIEWER_ROLE_KEY: VIEWER_PERMISSIONS,
    }
)


def default_role_bundles() -> dict[str, tuple[str, ...]]:
    return {key: tuple(permissions) for key, permissions in DEFAULT_ROLE_BUNDLES.items()}


__all__ = [
    "ALL_PERMISSIONS",
    "DEFAULT_ROLE_BUNDLES",
    "OPERATOR_ROLE_KEY",
    "OWNER_ROLE_KEY",
    "PERMISSION_ADMIN_CONFIG",
    "PERMISSION_ADMIN_USERS",
    "PERMISSION_AUDIT_READ",
    "PERMISSION_BACKUP_EXPORT",
    "PERMISSION_BACKUP_RESTORE",
    "PERMISSION_CONTACTS_READ",
    "PERMISSION_CONTACTS_WRITE",
    "PERMISSION_FINANCE_READ",
    "PERMISSION_FINANCE_WRITE",
    "PERMISSION_INVENTORY_READ",
    "PERMISSION_INVENTORY_WRITE",
    "PERMISSION_INVOICES_READ",
    "PERMISSION_INVOICES_WRITE",
    "PERMISSION_JOBS_READ",
    "PERMISSION_JOBS_WRITE",
    "PERMISSION_LOGS_READ",
    "PERMISSION_MANUFACTURING_READ",
    "PERMISSION_MANUFACTURING_RUN",
    "PERMISSION_RECIPES_READ",
    "PERMISSION_RECIPES_WRITE",
    "PERMISSION_SETTINGS_MANAGE",
    "PERMISSION_SETTINGS_READ",
    "PERMISSION_SESSIONS_MANAGE",
    "PERMISSION_SYSTEM_ADMIN",
    "PERMISSION_SYSTEM_READ",
    "PERMISSION_SYSTEM_RESTART",
    "PERMISSION_UPDATES_CHECK",
    "PERMISSION_UPDATES_STAGE",
    "PERMISSION_USERS_MANAGE",
    "PERMISSION_USERS_READ",
    "VIEWER_ROLE_KEY",
    "default_role_bundles",
]
