name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          pip install pytest

      - name: Stamp SPDX headers (idempotent)
        run: python tools/add_spdx_headers.py

      - name: Check SPDX headers
        run: python tools/check_spdx_headers.py

      - name: Check plugin LICENSE files
        run: python tools/check_licenses.py

      - name: Run tests (if any)
        run: |
          if [ -d tests ]; then pytest -q; else echo "No tests/ directory"; fi

      - name: Upload artifacts (logs/data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tgc-artifacts
          path: |
            logs/**
            data/**
          if-no-files-found: ignore
